const CURRENCIES = [
  { id: 93, name: 'Bitcoin (BTC)' },
  { id: 43, name: 'Bitcoin BEP20 (BTC)' },
  { id: 139, name: 'Ethereum (ETH)' },
  { id: 212, name: 'Ethereum BEP20 (ETH)' },
  { id: 160, name: 'Ether Classic (ETC)' },
  { id: 99, name: 'Litecoin (LTC)' },
  { id: 161, name: 'Ripple (XRP)' },
  { id: 149, name: 'Monero (XMR)' },
  { id: 115, name: 'Dogecoin (DOGE)' },
  { id: 138, name: 'Polygon (MATIC)' },
  { id: 140, name: 'Dash (DASH)' },
  { id: 162, name: 'Zcash (ZEC)' },
  { id: 163, name: 'Tether Omni (USDT)' },
  { id: 36, name: 'Tether ERC20 (USDT)' },
  { id: 10, name: 'Tether TRC20 (USDT)' },
  { id: 208, name: 'Tether BEP20 (USDT)' },
  { id: 180, name: 'Tether SOL (USDT)' },
  { id: 268, name: 'Tether POLYGON (USDT)' },
  { id: 203, name: 'Dai (DAI)' },
  { id: 206, name: 'Binance USD (BUSD)' },
  { id: 173, name: 'NEM (XEM)' },
  { id: 177, name: 'NEO (NEO)' },
  { id: 178, name: 'EOS (EOS)' },
  { id: 179, name: 'IOTA (MIOTA)' },
  { id: 181, name: 'Cardano (ADA)' },
  { id: 182, name: 'Stellar (XLM)' },
  { id: 185, name: 'TRON (TRX)' },
  { id: 133, name: 'Waves (WAVES)' },
  { id: 48, name: 'OMG Network (OMG)' },
  { id: 124, name: 'Verge (XVG)' },
  { id: 168, name: '0x (ZRX)' },
  { id: 16, name: 'BinanceCoin BEP2 (BNB)' },
  { id: 19, name: 'BinanceCoin BEP20 (BNB)' },
  { id: 104, name: 'ICON (ICX)' },
  { id: 134, name: 'Komodo (KMD)' },
  { id: 27, name: 'BitTorrent (BTT)' },
  { id: 61, name: 'BAT (BAT)' },
  { id: 135, name: 'Ontology (ONT)' },
  { id: 26, name: 'Qtum (QTUM)' },
  { id: 197, name: 'Chainlink (LINK)' },
  { id: 198, name: 'Cosmos (ATOM)' },
  { id: 175, name: 'Tezos (XTZ)' },
  { id: 201, name: 'Polkadot (DOT)' },
  { id: 202, name: 'Uniswap (UNI)' },
  { id: 205, name: 'Ravencoin (RVN)' },
  { id: 82, name: 'Solana (SOL)' },
  { id: 8, name: 'VeChain (VET)' },
  { id: 210, name: 'Shiba ERC20 (SHIB)' },
  { id: 32, name: 'Shiba BEP20 (SHIB)' },
  { id: 216, name: 'Algorand (ALGO)' },
  { id: 213, name: 'Maker (MKR)' },
  { id: 217, name: 'Avalanche (AVAX)' },
  { id: 220, name: 'Yearn.finance (YFI)' },
  { id: 227, name: 'Decentraland (MANA)' },
  { id: 2, name: 'Terra (LUNA)' },
  { id: 76, name: 'NEAR Protocol (NEAR)' },
  { id: 144, name: 'Cronos (CRO)' },
  { id: 209, name: 'Toncoin (TON)' },
  { id: 286, name: 'PancakeSwap (CAKE)' },
];

const CURRENCY_LIST = [...new Set(CURRENCIES.map((currency) => /\(([^)]+)\)/.exec(currency.name)[1]))];

const EXCHANGES = [
  { id: 223, name: 'МультиВал' },
  { id: 346, name: 'UltraChange' },
  { id: 521, name: 'Шахта' },
  { id: 522, name: 'Касса' },
  { id: 546, name: 'SafelyChange' },
  { id: 614, name: 'El-Change' },
  { id: 615, name: 'Pocket-Exchange' },
  { id: 661, name: 'Ferma' },
  { id: 714, name: 'Top-Exchange' },
  { id: 757, name: 'ChangeNow' },
  { id: 761, name: 'FlashObmen' },
  { id: 923, name: 'HD-Change' },
  { id: 1013, name: 'AvanChange' },
  { id: 1125, name: 'IceSatoshi' },
  { id: 1174, name: 'FreeChange' },
];

module.exports = { CURRENCIES, CURRENCY_LIST, EXCHANGES };
